# Configuración básica del sitio
title: "Portafolio de Feliciano José Palacios Oscata"
description: "Colección de proyectos y trabajos en programación y desarrollo de software."

# Tema
theme: jekyll-theme-architect
