title: "Mi Portafolio"
description: "Bienvenido a mi portafolio donde muestro mis proyectos y habilidades."
baseurl: "" # Cambia esto si estás usando un subdirectorio
url: "https://tuusuario.github.io" # Cambia esto por tu URL de GitHub Pages
theme: jekyll-theme-architect

# Personaliza la navegación
nav:
  - title: "Inicio"
    url: "/"
  - title: "Proyectos"
    url: "/proyectos"
  - title: "Sobre Mí"
    url: "/sobre-mi"
  - title: "Contacto"
    url: "/contacto"

# Configura la apariencia
social:
  github: "https://github.com/Palacios1996"
  linkedin: "https://linkedin.com/in/tu-perfil"
