# Configuración básica del sitio
title: "Portafolio de Feliciano José Palacios Oscata"
description: "Este repositorio es una recopilación de mis estudios y proyectos académicos en programación y desarrollo de software."

# Tema
theme: jekyll-theme-architect
