# Configuración básica del sitio
title: "Bienvenido a mi portafolio"
description: "Este repositorio es una recopilación de mis estudios y proyectos académicos en programación y desarrollo de software."

# Tema
theme: jekyll-theme-architect
